"""Certificate management.

Two unrelated PKI worlds live side by side in a project directory — never mix them:

* ``webui-pki/`` — **our own CA** for WebUI access. Browsers present client
  certs issued here; nginx terminates the WebUI port and verifies them
  (``ssl_verify_client on`` + ``ssl_crl``). Modules: :mod:`ca`,
  :mod:`client_certs`, :mod:`crl`, :mod:`server_certs`.
* ``certs/`` — **TeddyCloud's own directory** (mounted into the container).
  ``certs/server/`` is auto-generated by TeddyCloud (``ca.der`` goes onto the
  box); ``certs/client/`` holds the irreplaceable certs dumped from the box.
  Modules: :mod:`box_certs`, plus the export half of :mod:`server_certs`.
"""
