"""Docker services submenu for the active project's compose stack."""

from __future__ import annotations

from pathlib import Path

from rich.table import Table

from teddycloudhelper import backup, docker_cli, ui, wizard
from teddycloudhelper import state as state_mod
from teddycloudhelper.menus import project as project_menu

MENU_ACTIONS: list[tuple[str, str]] = [
    ("Show service status", "status"),
    ("Start services (up -d)", "start"),
    ("Stop services", "stop"),
    ("Restart services", "restart"),
    ("Show recent logs", "logs"),
    ("Pull latest images", "pull"),
    ("Switch TeddyCloud image channel (latest / develop)", "image"),
    ("Reset project (down incl. volumes)", "reset"),
    ("Switch / adopt another project", "switch"),
    ("Back to main menu", "back"),
]


def _print_status(compose: docker_cli.Compose) -> None:
    services = compose.ps()
    if not services:
        ui.info_panel("No containers found for this project (not created yet?).")
        return
    table = Table(title=f"Services in {compose.project_dir}")
    table.add_column("Service")
    table.add_column("Container")
    table.add_column("State")
    table.add_column("Status")
    for svc in services:
        style = "green" if svc.state == "running" else "red"
        table.add_row(svc.service, svc.name, f"[{style}]{svc.state}[/{style}]", svc.status)
    ui.console.print(table)


def _dispatch(action: str, compose: docker_cli.Compose) -> Path | None:
    """Run one submenu action; returns a new project dir on switch."""
    if action == "status":
        _print_status(compose)
    elif action == "start":
        if not project_menu.confirm_required_ports(compose.project_dir):
            return None
        compose.up()
        _print_status(compose)
    elif action == "stop":
        compose.stop()
        _print_status(compose)
    elif action == "restart":
        compose.restart()
        _print_status(compose)
    elif action == "logs":
        _show_logs(compose)
    elif action == "pull":
        compose.pull()
        ui.info_panel("Images pulled.")
        if ui.confirm("Restart services now to use the new images?", default=True):
            compose.restart()
            _print_status(compose)
    elif action == "image":
        _switch_image(compose)
    elif action == "reset":
        _reset(compose)
    elif action == "switch":
        return project_menu.adopt_project()
    return None


def _show_logs(compose: docker_cli.Compose) -> None:
    """Show recent logs, optionally limited to one service to keep it readable."""
    services = sorted({svc.service for svc in compose.ps() if svc.service})
    service: str | None = None
    if len(services) > 1:
        # "" stands for "all" because ui.menu only deals in strings.
        choice = ui.menu(
            "Show logs for which service?",
            [("All services", "")] + [(name, name) for name in services],
        )
        service = choice or None
    mode = ui.menu(
        "How?",
        [
            ("Last 100 lines", "tail"),
            ("Follow live (stop with Ctrl-C)", "follow"),
        ],
    )
    if mode == "follow":
        ui.console.print("[dim]Following logs — Ctrl-C returns to the menu.[/dim]")
        compose.logs_follow(service=service)
    else:
        ui.console.print(compose.logs(tail=100, service=service) or "[dim](no log output)[/dim]")


def _switch_image(compose: docker_cli.Compose) -> None:
    project = compose.project_dir
    state = state_mod.load_state(project)
    tag = ui.menu(
        f"Current channel: {state.teddycloud_image_tag} — switch to?",
        [
            ("latest — stable releases (recommended)", "latest"),
            ("develop — newest features, may break", "develop"),
        ],
    )
    if tag == state.teddycloud_image_tag:
        ui.info_panel(f"Already on {tag!r} — nothing to do.")
        return
    compose_file = docker_cli.find_compose_file(project)
    foreign = compose_file is not None and "Generated by TeddyCloudHelper" not in (
        compose_file.read_text(encoding="utf-8", errors="replace")
    )
    if foreign and not ui.confirm(
        f"{compose_file.name} was not generated by this tool — switching "
        "the channel re-renders it from the template and REPLACES your "
        "custom file (a timestamped .bak is written). Continue?",
        default=False,
    ):
        return
    state.teddycloud_image_tag = tag
    state_mod.save_state(state, project)
    wizard.render_project(state, project)
    ui.info_panel(f"Compose file now uses the {tag!r} image.")
    if ui.confirm("Pull the image and restart now?", default=True):
        compose.pull()
        compose.up()
        _print_status(compose)


def _reset(compose: docker_cli.Compose) -> None:
    project = compose.project_dir
    if not ui.confirm(
        "This stops and removes ALL containers, networks and Docker volumes of "
        "this project. Data in named volumes (adopted installs often keep "
        "TeddyCloud's config, certs and content there) is deleted PERMANENTLY. "
        "Continue?",
        default=False,
    ):
        return
    if ui.confirm("Create a backup of config + certificates first?", default=True):
        try:
            path = backup.create_backup(project)
            ui.info_panel(f"Backup written: {path}")
        except backup.BackupError as exc:
            ui.error_panel(str(exc), title="Backup failed")
            if not ui.confirm("Reset anyway, WITHOUT a backup?", default=False):
                return
    typed = ui.ask_text(
        f"Type the project folder name ({project.name!r}) to confirm the reset:"
    )
    if typed.strip() != project.name:
        ui.info_panel("Name did not match — reset cancelled.")
        return
    compose.down(volumes=True)
    ui.info_panel(
        "Containers, networks and volumes removed.\n\n"
        "Files in the project directory itself (bind mounts like certs/, "
        "config/, content/ and the generated configs) are NOT touched — "
        "delete them manually if you want a truly clean slate, but keep "
        "certs/client/ (the dumped box certs are irreplaceable!).",
        title="Project reset",
    )


def run() -> None:
    """Submenu loop. Mirrors the main loop: errors render red and never crash."""
    project = project_menu.active_project()
    if project is None:
        return
    while True:
        compose = docker_cli.Compose(project)
        ui.console.print(f"Active project: [bold]{project}[/bold]")
        try:
            action = ui.menu("Docker services", MENU_ACTIONS)
        except ui.Cancelled:
            return
        if action == "back":
            return
        try:
            project = _dispatch(action, compose) or project
        except ui.Cancelled:
            continue
        except (docker_cli.DockerError, state_mod.StateError, ValueError) as exc:
            ui.error_panel(str(exc), title="Docker error")
